name: Trigger on Merge and Issue Creation

on:
  push:
    branches:
      - main  # Triggered on merge to 'main' branch

  issues:
    types: [opened]  # Triggered when an issue is created

jobs:
  handle-merge:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run script or task on merge
        run: |
          echo "Merge detected on main!"

  handle-issue:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest

    steps:
      - name: Assign Issue to Assignees
        uses: peter-evans/assign-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          assignees: 'dallinGson, SugarWookie, CoconinoKid53'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}