name: Convert Markdown to HTML

on:
  push:
    branches:
      - main
    paths:
      - 'internships/*.md'

jobs:
  convert-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Convert Markdown to HTML
        run: |
          for file in internships/*.md; do
            filename=$(basename -- "$file" .md)
            pandoc "$file" -o "internships/${filename}.html" --template=templates/internship-template.html
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add internships/*.html
          git commit -m "Generated HTML from Markdown for new internship entry"
          git push
