name: Convert Internship Markdown to HTML

on:
  push:
    branches:
      - main
    paths:
      - 'internships/*.md'
      - 'images/*'

jobs:
  convert-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get install -y pandoc

      - name: Create Internship Details Directory
        run: mkdir -p frontend/pages/internship-details

      - name: Convert Markdown to HTML
        run: |
          shopt -s nullglob  # Prevent errors if no files match
          files=(internships/*.md)
          
          if [ ${#files[@]} -eq 0 ]; then
            echo "No Markdown files found. Skipping conversion."
            exit 0
          fi
      
          for file in "${files[@]}"; do
            filename=$(basename -- "$file" .md)
      
            # Extract metadata
            name=$(grep -oP '(?<=name: ).*' "$file" | head -1)
            company=$(grep -oP '(?<=company: ).*' "$file" | head -1)
            position=$(grep -oP '(?<=position: ).*' "$file" | head -1)
            image=$(grep -oP '(?<=image: ).*' "$file" | head -1)
            summary=$(awk '/## Internship Details/,/## Key Responsibilities/' "$file" | sed -e '1d' -e '$d' | tr '\n' ' ')
            responsibilities=$(awk '/## Key Responsibilities/,/## Skills Gained/' "$file" | sed -e '1d' -e '$d' | sed 's/^/- /' | tr '\n' ' ')
            skills=$(awk '/## Skills Gained/,/^$/' "$file" | sed -e '1d' -e '$d' | sed 's/^/- /' | tr '\n' ' ')
            reflection=$(awk '/## Intern Reflection/,/## Video Summary/' "$file" | sed -e '1d' -e '$d' | tr '\n' ' ')
            video_link=$(grep -oP '(?<=iframe src=").*(?=")' "$file" | head -1)
      
            # Convert to HTML
            pandoc "$file" -o "frontend/pages/internship-details/${filename}.html" \
              --template=templates/internship-template.html \
              -V name="$name" -V company="$company" -V position="$position" \
              -V image="$image" -V summary="$summary" -V responsibilities="$responsibilities" \
              -V skills="$skills" -V reflection="$reflection" -V video_link="$video_link"
          done

      - name: Ensure Internships Page Exists
        run: |
          if [ ! -f frontend/pages/internships.html ]; then
            echo "ERROR: frontend/pages/internships.html not found!"
            exit 1
          fi

      - name: Update Internships Page with Tiles
        run: |
            internship_tiles=""
            for file in frontend/pages/internship-details/*.html; do
              filename=$(basename -- "$file" .html)
  
              # Extract the intern's name, company name, and image from the Markdown
              name=$(grep -oP '(?<=name: ).*' "internships/$filename.md" | head -1)
              company=$(grep -oP '(?<=company: ).*' "internships/$filename.md" | head -1)
              image=$(grep -oP '(?<=image: ).*' "internships/$filename.md" | head -1)
  
              internship_tiles+="
                  <a href=\"./internship-details/${filename}.html\" class=\"internship-tile\">\n
                      <div class=\"internship-banner\" style=\"background-image: url(${image});\">\n
                          <div class=\"internship-info\">${name} - ${company}</div>\n
                      </div>\n
                      <p>Click to view internship details</p>\n
                  </a>"
            done
  
            # Corrected: Write `awk` output back into internships.html
            awk -v tiles="$internship_tiles" '
              /<h2>Featured Student Internships<\/h2>/ {print; print "<div class=\"featured-internships\">"; print tiles; print "</div>"; next}
              {print}
            ' frontend/pages/internships.html > frontend/pages/internships.tmp && mv frontend/pages/internships.tmp frontend/pages/internships.html

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add frontend/pages/internship-details/*.html frontend/pages/internships.html
          git commit -m "Converted Markdown to HTML and updated internship tiles with images" || echo "No changes to commit"
          git push