name: Convert Internship Markdown to HTML

on:
  push:
    branches:
      - main
    paths:
      - 'internships/*.md'
      - 'images/*'

jobs:
  convert-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Create Internship Details Directory
        run: mkdir -p frontend/pages/internship-details

      - name: Convert Markdown to HTML
        run: |
          for file in internships/*.md; do
            filename=$(basename -- "$file" .md)
            output_file="frontend/pages/internship-details/${filename}.html"

            # Extract metadata (with default values)
            name=$(grep -oP '(?<=name: ).*' "$file" | head -1 || echo "Unknown Intern")
            company=$(grep -oP '(?<=company: ).*' "$file" | head -1 || echo "Unknown Company")
            position=$(grep -oP '(?<=position: ).*' "$file" | head -1 || echo "Intern")
            image=$(grep -oP '(?<=image: ).*' "$file" | head -1 || echo "default.jpg")
            summary=$(awk '/## Internship Details/,/## Key Responsibilities/' "$file" | sed -e '1d' -e '$d' | tr '\n' ' ')
            responsibilities=$(awk '/## Key Responsibilities/,/## Skills Gained/' "$file" | sed -e '1d' -e '$d' | sed 's/^/- /' | tr '\n' ' ')
            skills=$(awk '/## Skills Gained/,/^$/' "$file" | sed -e '1d' -e '$d' | sed 's/^/- /' | tr '\n' ' ')
            reflection=$(awk '/## Intern Reflection/,/## Video Summary/' "$file" | sed -e '1d' -e '$d' | tr '\n' ' ')
            video_link=$(grep -oP '(?<=iframe src=").*(?=")' "$file" | head -1 || echo "")

            # Ensure the template file exists
            if [[ ! -f templates/internship-template.html ]]; then
              echo "ERROR: Template file is missing!"
              exit 1
            fi

            # Convert to HTML
            pandoc "$file" -o "$output_file" \
              --template=templates/internship-template.html \
              -V name="$name" -V company="$company" -V position="$position" \
              -V image="$image" -V summary="$summary" -V responsibilities="$responsibilities" \
              -V skills="$skills" -V reflection="$reflection" -V video_link="$video_link"

          done

      - name: Ensure Internships Page Exists
        run: |
          if [[ ! -f ./frontend/pages/internships.html ]]; then
            echo "ERROR: frontend/pages/internships.html not found!"
            exit 1
          fi

      - name: Remove Old Internship Tiles Between <h2> and </section>
        run: |
          # Delete everything between <h2> and </section> but keep the tags
          sed -i '/<h2>Featured Student Internships<\/h2>/,/<\/section>/ {
          }' frontend/pages/internships.html
        
        
      - name: Update Internships Page with Tiles
        run: |
          internship_tiles=""
          
          # Gather internship tiles for the updated internships
          for file in frontend/pages/internship-details/*.html; do
            filename=$(basename -- "$file" .html)
            md_file="internships/$filename.md"

            if [[ ! -f "$md_file" ]]; then
              echo "Skipping $filename: Markdown source not found."
              continue
            fi

            name=$(grep -oP '(?<=name: ).*' "$md_file" | head -1 || echo "Unknown Intern")
            company=$(grep -oP '(?<=company: ).*' "$md_file" | head -1 || echo "Unknown Company")
            image=$(grep -oP '(?<=image: ).*' "$md_file" | head -1 || echo "images/placeholder.jpg")  # Updated path for image

            internship_tiles+="
                <a href=\"./internship-details/${filename}.html\" class=\"internship-tile\">
                    <div class=\"internship-info\">${name} - ${company}</div>
                    <img src=\"${image}\" alt=\"Internship Image\" class=\"internship-image\">
                    <p>Click to view internship details</p>
                </a>"

          done

          # Add new internship tiles section after <h2> and before </section>
          awk -v tiles="$internship_tiles" '
            /<h2>Featured Student Internships<\/h2>/ {print; print "<div class=\"featured-internships\">"; print tiles; print "</div>"; next}
            {print}
          ' frontend/pages/internships.html > frontend/pages/internships.tmp && mv frontend/pages/internships.tmp frontend/pages/internships.html

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add frontend/pages/internship-details/*.html frontend/pages/internships.html
          git commit -m "Updated internship HTML files and internship tiles with images" || echo "No changes to commit"
          git push
